### ISSUE TITLE
Did not build on Java 8 + Ubuntu 14.04

### ISSUE THREAD

**Issue by icha024** [ivanceras/crypto-gwt#2]
I was having a play with this, wanting to use the emul package. Just converting some code from Java to Javascript with GWT.... but master branch doesn't seem to compile for me with 'mvn install' on Java 8 under Ubuntu 14.04.

Ian

[INFO] Compiling 33 source files to /home/ian/git/crypto-gwt/target/test-classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.949s
[INFO] Finished at: Sun Jan 31 18:30:10 GMT 2016
[INFO] Final Memory: 28M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:testCompile (default-testCompile) on project crypto-gwt: Compilation failure: Compilation failure:
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:[5,28] SHA is internal proprietary API and may be removed in a future release
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:[6,28] error: SHA2 is not public in sun.security.provider; cannot be accessed from outside package
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:[10,30] error: AESCipher is not public in com.sun.crypto.provider; cannot be accessed from outside package
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwt/provider/client/GwtTstSecureRandom.java:[37,25] error: next(int) has protected access in SecureRandom
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwt/provider/client/GwtTstSecureRandom.java:[54,25] error: next(int) has protected access in SecureRandom
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwt/provider/client/GwtTstNistRandomNumberTests.java:[39,61] error: next(int) has protected access in SecureRandom
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:[25,16] error: cannot find symbol
[ERROR] 
[ERROR] could not parse error message:   symbol:   class SHA2
[ERROR] location: class JceAdaptorProvider
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:28: error: cannot find symbol
[ERROR] new MessageDigestSpiFactory(SHA2.class));
[ERROR] ^
[ERROR] 
[ERROR] could not parse error message:   symbol:   class SHA2
[ERROR] location: class JceAdaptorProvider
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:34: warning: SHA is internal proprietary API and may be removed in a future release
[ERROR] SHA.class.getName(),
[ERROR] ^
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:[37,44] SHA is internal proprietary API and may be removed in a future release
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:[43,16] error: cannot find symbol
[ERROR] 
[ERROR] could not parse error message:   symbol:   class AESCipher
[ERROR] location: class JceAdaptorProvider
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:46: error: cannot find symbol
[ERROR] new CipherSpiFactory(AESCipher.class));
[ERROR] ^
[ERROR] 
[ERROR] could not parse error message:   symbol:   class AESCipher
[ERROR] location: class JceAdaptorProvider
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:52: warning: SecureRandom is internal proprietary API and may be removed in a future release
[ERROR] sun.security.provider.SecureRandom.class.getName(),
[ERROR] ^
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/JceAdaptorProvider.java:[55,64] SecureRandom is internal proprietary API and may be removed in a future release
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/SecureRandomTest.java:[41,25] error: next(int) has protected access in SecureRandom
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/SecureRandomTest.java:[55,25] error: next(int) has protected access in SecureRandom
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/SecureRandomTest.java:[80,26] error: next(int) has protected access in SecureRandom
[ERROR] 
[ERROR] /home/ian/git/crypto-gwt/src/test/java/com/googlecode/cryptogwttests/SecureRandomTest.java:[100,28] error: next(int) has protected access in SecureRandom
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ivanceras** [comment]
Hi, this project is not maintained anymore

**Comment by icha024** [comment]
Was just about to add, I've found the other source at https://code.google.com/archive/p/crypto-gwt/ that has the emul bits

Sorry i'm really new to GWT.
